name: currency_type
description: Currency type for Dart and Flutter, a large numeric type, with exactly four digit after the decimal point, appropriate for financial calculations.
version: 0.0.3
homepage: https://github.com/tantowi/dart_currency_type

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:

dev_dependencies: 
  test: ^1.17.11

