name: currency
description: Dart currency type for Dart and Flutter.
version: 0.0.1
homepage: https://github.com/tantowi/dart_currency

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies: 
  test: ^1.17.11

